version: '3'

services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: topgunlab
    volumes:
      - db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017

volumes:
  db: